DESIGN_NAME = balanced_round_robin_arbiter

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../static_priority_arbiter/static_priority_arbiter.v
ADDITIONAL_RTL_SOURCES += ../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/fast_first_one/fast_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/shift_left/shift_left.v

include ../../common/common.mk
