DESIGN_NAME = round_robin_arbiter

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../static_priority_arbiter/static_priority_arbiter.v
ADDITIONAL_RTL_SOURCES += ../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/fast_first_one/fast_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_left/barrel_rotator_left.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_right/barrel_rotator_right.v

include ../../common/common.mk
