DESIGN_NAME = round_robin_arbiter
COMPILE_FLAGS_ICARUS = -g2012

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../static_priority_arbiter/static_priority_arbiter.v
ADDITIONAL_RTL_SOURCES += ../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_left/barrel_rotator_left.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_right/barrel_rotator_right.v

include ../../common/common.mk
