DESIGN_NAME = round_robin_arbiter

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../static_priority_arbiter/static_priority_arbiter.v
ADDITIONAL_RTL_SOURCES += ../small_round_robin_arbiter/small_round_robin_arbiter.v
ADDITIONAL_RTL_SOURCES += ../fast_round_robin_arbiter/fast_round_robin_arbiter.v
ADDITIONAL_RTL_SOURCES += ../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/fast_first_one/fast_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_left/barrel_rotator_left.v
ADDITIONAL_RTL_SOURCES += ../../operations/barrel_rotator_right/barrel_rotator_right.v
ADDITIONAL_RTL_SOURCES += ../../operations/rotate_left/rotate_left.v
ADDITIONAL_RTL_SOURCES += ../../operations/rotate_right/rotate_right.v
ADDITIONAL_RTL_SOURCES += ../../counter/wrapping_increment_counter/wrapping_increment_counter.v

include ../../common/common.mk
