DESIGN_NAME = gray

DESIGN_FILELISTS += binary_to_gray.design.filelist
DESIGN_FILELISTS += gray_to_binary.design.filelist

DESIGN_INCLISTS += binary_to_gray.design.inclist
DESIGN_INCLISTS += gray_to_binary.design.inclist

include ../../common/common.mk