DESIGN_NAME = static_priority_arbiter

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../../operations/fast_first_one/fast_first_one.v

include ../../common/common.mk
