DESIGN_NAME   = toggle_pulse_synchronizer

ADDITIONAL_RTL_SOURCES  = ../synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../pulse/edge_detector/edge_detector.v
ADDITIONAL_RTL_SOURCES += ../../flip_flop/toggle_flip_flop_with_asynchronous_reset/toggle_flip_flop_with_asynchronous_reset.v

include ../../common/common.mk
