DESIGN_NAME = hamming

DESIGN_FILELISTS += hamming_encoder.design.filelist
DESIGN_FILELISTS += hamming_checker.design.filelist
DESIGN_FILELISTS += hamming_block_checker.design.filelist
DESIGN_FILELISTS += hamming_corrector.design.filelist
DESIGN_FILELISTS += hamming_block_corrector.design.filelist
DESIGN_FILELISTS += hamming_block_packager.design.filelist
DESIGN_FILELISTS += hamming_block_extractor.design.filelist

DESIGN_INCLISTS += hamming_encoder.design.inclist
DESIGN_INCLISTS += hamming_checker.design.inclist
DESIGN_INCLISTS += hamming_block_checker.design.inclist
DESIGN_INCLISTS += hamming_corrector.design.inclist
DESIGN_INCLISTS += hamming_block_corrector.design.inclist
DESIGN_INCLISTS += hamming_block_packager.design.inclist
DESIGN_INCLISTS += hamming_block_extractor.design.inclist

include ../../common/common.mk
