DESIGN_NAME   = hamming_encoder
TOP_TESTBENCH = $(DESIGN_NAME)_tb_top

RTL_SOURCES  = $(DESIGN_NAME).sv
RTL_SOURCES += hamming_block_packager.sv
RTL_SOURCES += $(DESIGN_NAME)_tb_sub.sv
RTL_SOURCES += $(DESIGN_NAME)_tb_top.sv

include ../../common/common.mk
