DESIGN_NAME = first_one
COMPILE_FLAGS_ICARUS = -g2012

RTL_INCLUDES  = ../../common

ADDITIONAL_RTL_SOURCES  = ../small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../fast_first_one/fast_first_one.v

include ../../common/common.mk
