DESIGN_NAME   = asynchronous_fifo
COMPILE_FLAGS = -g2012

RTL_INCLUDES  = ../../common
ADDITIONAL_RTL_SOURCES  = ../../timing/vector_synchronizer/vector_synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../timing/synchronizer/synchronizer.v

include ../../common/common.mk
