DESIGN_NAME = onehot

DESIGN_FILELISTS += binary_to_onehot.design.filelist
DESIGN_FILELISTS += onehot_to_binary.design.filelist

DESIGN_INCLISTS += binary_to_onehot.design.inclist
DESIGN_INCLISTS += onehot_to_binary.design.inclist

include ../../common/common.mk