DESIGN_NAME   = pulse_synchronizer_with_busy
COMPILE_FLAGS = -g2012

ADDITIONAL_RTL_SOURCES  = ../synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../pulse/rising_edge_detector/rising_edge_detector.v

include ../../common/common.mk
