DESIGN_NAME = repetition

DESIGN_FILELISTS += repetition_encoder.design.filelist
DESIGN_FILELISTS += repetition_checker.design.filelist
DESIGN_FILELISTS += repetition_corrector.design.filelist
DESIGN_FILELISTS += repetition_block_checker.design.filelist
DESIGN_FILELISTS += repetition_block_corrector.design.filelist

DESIGN_INCLISTS  += repetition_encoder.design.inclist
DESIGN_INCLISTS  += repetition_checker.design.inclist
DESIGN_INCLISTS  += repetition_corrector.design.inclist
DESIGN_INCLISTS  += repetition_block_checker.design.inclist
DESIGN_INCLISTS  += repetition_block_corrector.design.inclist

include ../../common/common.mk