DESIGN_NAME = parity

DESIGN_FILELISTS += parity_block_checker.design.filelist
DESIGN_FILELISTS += parity_checker.design.filelist
DESIGN_FILELISTS += parity_encoder.design.filelist

DESIGN_INCLISTS  += parity_block_checker.design.inclist
DESIGN_INCLISTS  += parity_checker.design.inclist
DESIGN_INCLISTS  += parity_encoder.design.inclist

include ../../common/common.mk
