DESIGN_NAME = out_of_order_buffer
COMPILE_FLAGS_ICARUS = -g2012

RTL_INCLUDES  = ../../../common

ADDITIONAL_RTL_SOURCES  = ../../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../../operations/fast_first_one/fast_first_one.v
ADDITIONAL_RTL_SOURCES += ../../../operations/small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/onehot/onehot_to_binary.v

include ../../../common/common.mk
