DESIGN_NAME   = pulse_synchronizer
COMPILE_FLAGS_ICARUS = -g2012

ADDITIONAL_RTL_SOURCES  = ../synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../pulse/rising_edge_detector/rising_edge_detector.v

include ../../common/common.mk
