DESIGN_NAME   = valid_ready_asynchronous_advanced_fifo

RTL_INCLUDES  = ../../../common

ADDITIONAL_RTL_SOURCES  = ../../read_write_enable/asynchronous_advanced_fifo/asynchronous_advanced_fifo.v
ADDITIONAL_RTL_SOURCES += ../../../timing/vector_synchronizer/vector_synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../../timing/synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/grey/binary_to_grey.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/grey/grey_to_binary.v

include ../../../common/common.mk
