DESIGN_NAME   = asynchronous_advanced_fifo
COMPILE_FLAGS = -g2012

RTL_INCLUDES  = ../../../common
ADDITIONAL_RTL_SOURCES  = ../../../timing/vector_synchronizer/vector_synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../../timing/synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/grey/binary_to_grey.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/grey/grey_to_binary.v

include ../../../common/common.mk
