DESIGN_NAME = bcd

DESIGN_FILELISTS += binary_to_bcd.design.filelist
DESIGN_FILELISTS += bcd_to_binary.design.filelist

DESIGN_INCLISTS += binary_to_bcd.design.inclist
DESIGN_INCLISTS += bcd_to_binary.design.inclist

include ../../common/common.mk
