DESIGN_NAME = valid_ready_out_of_order_buffer
DESIGN_EXTENSION = sv

RTL_INCLUDES  = ../../../common

ADDITIONAL_RTL_SOURCES  = ../../read_write_enable/out_of_order_buffer/out_of_order_buffer.sv
ADDITIONAL_RTL_SOURCES += ../../../operations/first_one/first_one.v
ADDITIONAL_RTL_SOURCES += ../../../operations/fast_first_one/fast_first_one.v
ADDITIONAL_RTL_SOURCES += ../../../operations/small_first_one/small_first_one.v
ADDITIONAL_RTL_SOURCES += ../../../encoding/onehot/onehot_to_binary.v

include ../../../common/common.mk
