DESIGN_NAME   = feedback_pulse_synchronizer

ADDITIONAL_RTL_SOURCES  = ../synchronizer/synchronizer.v
ADDITIONAL_RTL_SOURCES += ../../pulse/rising_edge_detector/rising_edge_detector.v

include ../../common/common.mk
