DESIGN_NAME = grey

DESIGN_FILELISTS += binary_to_grey.design.filelist
DESIGN_FILELISTS += grey_to_binary.design.filelist

DESIGN_INCLISTS += binary_to_grey.design.inclist
DESIGN_INCLISTS += grey_to_binary.design.inclist

include ../../common/common.mk