DESIGN_NAME = extended_hamming

DESIGN_FILELISTS += extended_hamming_encoder.design.filelist
DESIGN_FILELISTS += extended_hamming_checker.design.filelist
DESIGN_FILELISTS += extended_hamming_block_checker.design.filelist
DESIGN_FILELISTS += extended_hamming_corrector.design.filelist
DESIGN_FILELISTS += extended_hamming_block_corrector.design.filelist
DESIGN_FILELISTS += extended_hamming_block_packer.design.filelist
DESIGN_FILELISTS += extended_hamming_block_unpacker.design.filelist

DESIGN_INCLISTS += extended_hamming_encoder.design.inclist
DESIGN_INCLISTS += extended_hamming_checker.design.inclist
DESIGN_INCLISTS += extended_hamming_block_checker.design.inclist
DESIGN_INCLISTS += extended_hamming_corrector.design.inclist
DESIGN_INCLISTS += extended_hamming_block_corrector.design.inclist
DESIGN_INCLISTS += extended_hamming_block_packer.design.inclist
DESIGN_INCLISTS += extended_hamming_block_unpacker.design.inclist

include ../../common/common.mk
