DESIGN_NAME   = valid_ready_advanced_fifo
COMPILE_FLAGS_ICARUS = -g2012

RTL_INCLUDES  = ../../../common

ADDITIONAL_RTL_SOURCES  = ../../read_write_enable/advanced_fifo/advanced_fifo.v

include ../../../common/common.mk
